image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
    
tasks:
  - name: Excercism terminal
    command: |
        # Persist Exercism config
        mkdir -p .exercism-config
        WS_DIR=${PWD}
        (cd ~/.config && ln -s ${WS_DIR}/.exercism-config exercism)
        
        # Open instructions in VS Code
        code INSTRUCTIONS.md

        # Leave a friendly message about the terminal
        echo "Here's a terminal for using the excerism CLI tool 💪"

github:
  prebuilds:
    main: true
