image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
    
tasks:
  - name: Persist Excercism config
    command: |
        mkdir -p .exercism-config
        WS_DIR=${PWD}
        (cd ~/.config && ln -s ${WS_DIR}/.exercism-config exercism) & kill -9 "$BASHPID"
  - name: INSTRUCTIONS
    command: code INSTRUCTIONS.md & kill -9 "$BASHPID"
  - name: Excercism terminal
    command: echo "Here's a terminal for using the excerism CLI tool 💪"

github:
  prebuilds:
    main: true
